### PR TITLE
Add RAID-Z support and refactor to support Chef 13

### PR DESCRIPTION
**Pull request by rhass**
- Added support for RAID-Z pools
 - Performed minor refactored of resource to support Chef 13 by using
   custom resources instead of the older LWRP resources.

Resolves [Issue #5](https://github.com/marthag8/zpool/issues/5)

Signed-off-by: Ryan Hass <rhass@users.noreply.github.com>

### CODE REVIEW

**Comment by tas50** [comment]
You should switch the Travis config over to using ChefDK so you don't have to both managing gems anymore. 

Here's a sample config with Delivery local mode for the testing

https://github.com/chef-cookbooks/aix/blob/master/.travis.yml

**Comment by rhass** [comment]
@tas50 Already did it! :smile: 
https://github.com/marthag8/zpool/pull/6/files#diff-354f30a63fb0907d4ad57269548329e3

However, I didn't delete the Gemfile and Gemfile.lock.

**Comment by rhass** [comment]
@tas50 I haven't heard anything from @marthag8 -- I think we will need to fork this in the `chef-cookbooks` repo.

I also am almost finished with a *major* rewrite of the ZFS cookbook @marthag8 originally wrote. https://github.com/marthag8/zfs/compare/master...rhass:zfs-rewrite

The ZFS cookbook needs tests, and I probably should add a couple other actions to make feature parity with the previous version. Nevertheless, both of these cookbooks are supported on Linux and FreeBSD now as well.

**Comment by rhass** [comment]
Closing this PR in favor of: https://github.com/chef-cookbooks/chef_zpool/pull/1

**Pull request closed without merging**
